[build]
  command = "npm run build"
  publish = ".next"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/api/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
